# Generated by Django 4.0.1 on 2022-03-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_division_inventory_item_delete_post_inventory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.IntegerField(choices=[(0, 'stock_in'), (1, 'stock_out')]),
        ),
    ]
