# Generated by Django 4.0.1 on 2022-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_inventory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.IntegerField(choices=[(0, 'Stock In'), (1, 'Stock Out')]),
        ),
    ]
