# Generated by Django 4.0.1 on 2022-03-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_inventory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.division', unique=True),
        ),
    ]
